package config

type configKey uint

const (
	BASE_WEB_URL configKey = iota
	BASE_API_URL
	SENDGRID_API_KEY
	PAYTM_MID
	PAYTM_SALES_WALLET_GUID
	PAYTM_AES
	AMPLITUDE_API_KEY
	FACEBOOK_APP_ID
	FACEBOOK_APP_SECRET
	GOOGLE_CLIENT_ID
	GOOGLE_CLIENT_SECRET
	DB_DATABASE_NAME
	DB_HOST
	DB_USERNAME
	IP_ADDRESS
	AWS_REGION
	AWS_SECRET_KEY
	AWS_ACCESS_ID
	S3_BUCKET
	MONGO_HOST
	MONGO_DB_NAME
)

var configKeyNames = map[configKey]string{
	BASE_WEB_URL:            "BASE_WEB_URL",
	BASE_API_URL:            "BASE_API_URL",
	SENDGRID_API_KEY:        "SENDGRID_API_KEY",
	PAYTM_MID:               "PAYTM_MID",
	PAYTM_SALES_WALLET_GUID: "PAYTM_SALES_WALLET_GUID",
	PAYTM_AES:               "PAYTM_AES",
	AMPLITUDE_API_KEY:       "AMPLITUDE_API_KEY",
	FACEBOOK_APP_ID:         "FACEBOOK_APP_ID",
	FACEBOOK_APP_SECRET:     "FACEBOOK_APP_SECRET",
	GOOGLE_CLIENT_ID:        "GOOGLE_CLIENT_ID",
	GOOGLE_CLIENT_SECRET:    "GOOGLE_CLIENT_SECRET",
	DB_DATABASE_NAME:        "DB_DATABASE_NAME",
	DB_HOST:                 "DB_HOST",
	DB_USERNAME:             "DB_USERNAME",
	IP_ADDRESS:              "IP_ADDRESS",
	AWS_REGION:              "AWS_REGION",
	AWS_SECRET_KEY:          "AWS_SECRET_KEY",
	AWS_ACCESS_ID:           "AWS_ACCESS_ID",
	S3_BUCKET:               "S3_BUCKET",
	MONGO_HOST:              "MONGO_HOST",
	MONGO_DB_NAME:           "MONGO_DB_NAME",
}

func (c *configKey) String() string {
	return configKeyNames[*c]
}
